name: CI/CD for pull request
on:
  pull_request:
    branches:
     - prod

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build App
        shell: bash
        run: |
          npm install
          npm run build

      - name: Serve app
        shell: bash
        run: |
          nohup npx http-server ./dist/climactif/browser -p 3000 > server.log 2>&1 &
          sleep 5
          echo "Server started on port 3000"

#      - name: Run Lighthouse CI
#        run: |
#          npm install -g @lhci/cli@0.15.x
#          lhci autorun --config=./accessibility/lighthouse-ci/.lighthouserc.js
#        env:
#          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run Pa11y Audit
        uses: ./accessibility/pa11y-ci
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Run Ecoindex Audit
        uses: ./accessibility/ecoindex-ci
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

