name: CI/CD for pull request
on:
  pull_request:
    branches:
     - dev

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build App
        shell: bash
        run: |
          npm install
          npm run build

      - name: Serve app
        shell: bash
        run: |
          npm run serve > server.log 2>&1 &
          sleep 10
          echo "Server started on port 4200"

#      - name: Run Pa11y Audit
#        uses: ./accessibility/pa11y-ci
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Run Ecoindex Audit
        uses: ./accessibility/ecoindex-ci
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Lighthouseci Audit
        uses: ./accessibility/lighthouse-ci
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}



